import {createHmac} from 'crypto';import {Hono} from 'hono';import {and,eq,inArray} from 'drizzle-orm';import {requireDatabaseUrl,requireQ360StagingDatabaseGuard} from '../utils/env.js';
requireQ360StagingDatabaseGuard('verify:staff-hr');requireDatabaseUrl();process.env.JWT_SECRET||='staff-hr-verification';delete process.env.RESEND_API_KEY;process.env.NODE_ENV='test';
const {db,first,closeDatabase}=await import('../db/client.js');const {auditLogs,businesses,otpCodes,staffInvitations,staffMembers,users}=await import('../db/schema.js');const {default:authRoutes}=await import('../routes/auth.js');const {default:staffRoutes}=await import('../routes/staff.js');const app=new Hono();app.route('/api/auth',authRoutes);app.route('/api/staff',staffRoutes);
const businessesUnderTest=['biz_verify_staff_a','biz_verify_staff_b'],usersUnderTest=['usr_verify_staff_owner','usr_verify_staff_existing'],emails=['invited-staff@example.com','existing-staff@example.com'];
const token=(u:string,b:string)=>{const e=(v:unknown)=>Buffer.from(JSON.stringify(v)).toString('base64url'),n=Math.floor(Date.now()/1000),h=e({alg:'HS256',typ:'JWT'}),p=e({sub:u,email:`${u}@example.com`,role:'admin',businessId:b,iat:n,exp:n+3600}),s=createHmac('sha256',process.env.JWT_SECRET!).update(`${h}.${p}`).digest('base64url');return`${h}.${p}.${s}`};
const request=(path:string,init?:RequestInit,t?:string)=>app.request(path,{...init,headers:{...(t?{Authorization:`Bearer ${t}`} :{}),'Content-Type':'application/json',...init?.headers}});
const signIn=async(email:string)=>{let out='';const original=console.log;console.log=(...a:unknown[])=>{out+=a.map(String).join(' ')+'\n'};try{const login=await request('/api/auth/login',{method:'POST',body:JSON.stringify({email})});if(login.status!==200)throw new Error(`OTP request ${login.status}`);const code=out.match(new RegExp(`\\[DEV OTP\\] Code for ${email}: (\\d{6})`))?.[1];if(!code)throw new Error('OTP not captured');const verified=await request('/api/auth/verify',{method:'POST',body:JSON.stringify({email,code})});if(verified.status!==200)throw new Error(`OTP verify ${verified.status} ${await verified.text()}`);return verified.json() as Promise<{token:string;user:{role:string;moduleAccess:string[];primaryWorkspace:string}}>;}finally{console.log=original}};
try{await db.delete(auditLogs).where(inArray(auditLogs.businessId,businessesUnderTest));await db.delete(staffInvitations).where(inArray(staffInvitations.businessId,businessesUnderTest));await db.delete(staffMembers).where(inArray(staffMembers.businessId,businessesUnderTest));await db.delete(otpCodes).where(inArray(otpCodes.email,emails));await db.delete(users).where(inArray(users.id,usersUnderTest));await db.delete(users).where(inArray(users.email,emails));await db.delete(businesses).where(inArray(businesses.id,businessesUnderTest));await db.insert(businesses).values([{id:businessesUnderTest[0],name:'Staff Restaurant A',type:'restaurant'},{id:businessesUnderTest[1],name:'Existing Business B',type:'restaurant'}]);await db.insert(users).values([{id:usersUnderTest[0],email:'owner-staff@example.com',role:'admin',businessId:businessesUnderTest[0],onboardingCompleted:true},{id:usersUnderTest[1],email:emails[1],role:'manager',businessId:businessesUnderTest[1],onboardingCompleted:true,primaryWorkspace:'/app/restaurant'}]);const owner=token(usersUnderTest[0],businessesUnderTest[0]);
 const invite=await request('/api/staff/invite',{method:'POST',body:JSON.stringify({name:'Invited Chef',email:emails[0],role:'kitchen',moduleAccess:['dashboard','kds'],shiftName:'Evening',shiftStart:'16:00',shiftEnd:'23:00'})},owner);if(invite.status!==201)throw new Error(`Invite failed ${invite.status} ${await invite.text()}`);const accepted=await signIn(emails[0]);const acceptedUser=await first(db.select().from(users).where(eq(users.email,emails[0]))),member=await first(db.select().from(staffMembers).where(and(eq(staffMembers.businessId,businessesUnderTest[0]),eq(staffMembers.email,emails[0])))),acceptedInvite=await first(db.select().from(staffInvitations).where(and(eq(staffInvitations.businessId,businessesUnderTest[0]),eq(staffInvitations.email,emails[0]))));if(acceptedUser?.businessId!==businessesUnderTest[0]||accepted.user.role!=='kitchen'||accepted.user.primaryWorkspace!=='/app/restaurant'||member?.status!=='active'||acceptedInvite?.status!=='accepted'||accepted.user.moduleAccess.join(',')!=='dashboard,kds')throw new Error('Invitation acceptance failed');
 const existingInvite=await request('/api/staff/invite',{method:'POST',body:JSON.stringify({name:'Existing Manager',email:emails[1],role:'cashier',moduleAccess:['pos','payments']})},owner);if(existingInvite.status!==201)throw new Error(`Existing invite ${existingInvite.status}`);await signIn(emails[1]);const established=await first(db.select().from(users).where(eq(users.email,emails[1]))),pending=await first(db.select().from(staffInvitations).where(and(eq(staffInvitations.businessId,businessesUnderTest[0]),eq(staffInvitations.email,emails[1]))));if(established?.businessId!==businessesUnderTest[1]||pending?.status!=='pending')throw new Error('Established account was transferred across businesses');
 console.log(JSON.stringify({staffPersisted:true,otpInvitationAccepted:true,roleAssigned:true,moduleAccessAssigned:true,shiftSaved:member?.shiftName==='Evening',existingAccountProtected:true,tenantIsolation:true},null,2));
}catch(e){console.error('Staff/HR verification failed:',e);process.exitCode=1}finally{await db.delete(auditLogs).where(inArray(auditLogs.businessId,businessesUnderTest));await db.delete(staffInvitations).where(inArray(staffInvitations.businessId,businessesUnderTest));await db.delete(staffMembers).where(inArray(staffMembers.businessId,businessesUnderTest));await db.delete(otpCodes).where(inArray(otpCodes.email,emails));await db.delete(users).where(inArray(users.id,usersUnderTest));await db.delete(users).where(inArray(users.email,emails));await db.delete(businesses).where(inArray(businesses.id,businessesUnderTest));await closeDatabase()}
