import { createHmac } from 'crypto';
import { Hono } from 'hono';
import { inArray } from 'drizzle-orm';
import { requireDatabaseUrl, requireQ360StagingDatabaseGuard } from '../utils/env.js';

requireQ360StagingDatabaseGuard('verify:public-identity');
requireDatabaseUrl();
process.env.JWT_SECRET ||= 'public-identity-verification-secret';
process.env.NODE_ENV = 'test';

const { db, closeDatabase } = await import('../db/client.js');
const { auditLogs, businessAssets, businesses, menuCategories, menuItems, restaurantMenus, users } = await import('../db/schema.js');
const { default: businessRoutes } = await import('../routes/business.js');
const { default: publicRoutes } = await import('../routes/public.js');

const businessIds=['biz_verify_public_a','biz_verify_public_b'];const userIds=['usr_verify_public_a','usr_verify_public_b'];
const menuIds=['menu_verify_public_a','menu_verify_public_b'];const categoryIds=['cat_verify_public_a','cat_verify_public_b'];
const app=new Hono();app.route('/api/business',businessRoutes);app.route('/api/public',publicRoutes);
const token=(userId:string,businessId:string)=>{const encode=(value:unknown)=>Buffer.from(JSON.stringify(value)).toString('base64url');const now=Math.floor(Date.now()/1000);const header=encode({alg:'HS256',typ:'JWT'});const payload=encode({sub:userId,email:`${userId}@example.com`,role:'admin',businessId,iat:now,exp:now+3600});const signature=createHmac('sha256',process.env.JWT_SECRET!).update(`${header}.${payload}`).digest('base64url');return`${header}.${payload}.${signature}`};
const authed=(authToken:string,path:string,init?:RequestInit)=>app.request(path,{...init,headers:{Authorization:`Bearer ${authToken}`,...init?.headers}});
try{
 await db.delete(auditLogs).where(inArray(auditLogs.businessId,businessIds));await db.delete(businessAssets).where(inArray(businessAssets.businessId,businessIds));await db.delete(menuItems).where(inArray(menuItems.businessId,businessIds));await db.delete(menuCategories).where(inArray(menuCategories.businessId,businessIds));await db.delete(restaurantMenus).where(inArray(restaurantMenus.businessId,businessIds));await db.delete(users).where(inArray(users.id,userIds));await db.delete(businesses).where(inArray(businesses.id,businessIds));
 await db.insert(businesses).values([{id:businessIds[0],name:'Public Restaurant A',type:'restaurant',country:'France',currency:'EUR'},{id:businessIds[1],name:'Private Restaurant B',type:'restaurant'}]);await db.insert(users).values(userIds.map((id,index)=>({id,email:`${id}@example.com`,role:'admin',businessId:businessIds[index]})));await db.insert(restaurantMenus).values(menuIds.map((id,index)=>({id,businessId:businessIds[index],name:'Main Menu',isActive:true})));await db.insert(menuCategories).values(categoryIds.map((id,index)=>({id,businessId:businessIds[index],menuId:menuIds[index],name:'Mains',sortOrder:0})));await db.insert(menuItems).values([{id:'item_verify_public_visible',businessId:businessIds[0],categoryId:categoryIds[0],name:'Visible Soup',description:'Fresh soup',price:850,isAvailable:true,prepTimeMinutes:8,imageUrl:null},{id:'item_verify_public_hidden',businessId:businessIds[0],categoryId:categoryIds[0],name:'Hidden Soup',price:900,isAvailable:false,prepTimeMinutes:8,imageUrl:null},{id:'item_verify_public_tenant_b',businessId:businessIds[1],categoryId:categoryIds[1],name:'Tenant B Secret',price:100,isAvailable:true,prepTimeMinutes:1,imageUrl:null}]);
 const auth=token(userIds[0],businessIds[0]);const profileResponse=await authed(auth,'http://verify.local/api/business/profile');if(profileResponse.status!==200)throw new Error(`Profile failed ${profileResponse.status}`);const profile=await profileResponse.json() as {publicCode:string};if(!/^Q360-[A-F0-9]{8}$/.test(profile.publicCode))throw new Error(`Unsafe public code ${profile.publicCode}`);
 const form=new FormData();form.set('logo',new File([new Uint8Array([137,80,78,71])],'logo.png',{type:'image/png'}));const upload=await authed(auth,'http://verify.local/api/business/logo',{method:'POST',body:form});if(upload.status!==200)throw new Error(`Logo upload failed ${upload.status} ${await upload.text()}`);const uploaded=await upload.json() as {logoUrl:string};const logo=await app.request(uploaded.logoUrl);if(logo.status!==200||logo.headers.get('content-type')!=='image/png')throw new Error('Public logo fallback failed');
 const menu=await app.request(`http://verify.local/api/public/businesses/${profile.publicCode}/menu`);if(menu.status!==200)throw new Error(`Public menu failed ${menu.status}`);const menuBody=await menu.json() as {categories:{items:{name:string}[]}[]};const names=menuBody.categories.flatMap(category=>category.items.map(item=>item.name));if(names.join(',')!=='Visible Soup'||names.includes('Tenant B Secret'))throw new Error(`Public menu leaked unavailable or cross-tenant items: ${names}`);
 const connection=await app.request(`http://verify.local/api/public/businesses/${profile.publicCode}`);const connectionText=await connection.text();if(connection.status!==200||connectionText.includes(businessIds[0])||connectionText.includes('email'))throw new Error('Connection identity exposed private fields');
 const disabled=await authed(auth,'http://verify.local/api/business/public-menu',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:false})});if(disabled.status!==200)throw new Error('Public menu disable failed');const hidden=await app.request(`http://verify.local/api/public/businesses/${profile.publicCode}/menu`);if(hidden.status!==404)throw new Error('Disabled public menu remained visible');
 console.log(JSON.stringify({safePublicCode:true,logoUpload:true,publicMenuAvailableItemsOnly:true,tenantIsolation:true,privateFieldsHidden:true,disableEnforced:true},null,2));
}catch(error){console.error('Public identity verification failed:',error);process.exitCode=1}finally{await db.delete(auditLogs).where(inArray(auditLogs.businessId,businessIds));await db.delete(businessAssets).where(inArray(businessAssets.businessId,businessIds));await db.delete(menuItems).where(inArray(menuItems.businessId,businessIds));await db.delete(menuCategories).where(inArray(menuCategories.businessId,businessIds));await db.delete(restaurantMenus).where(inArray(restaurantMenus.businessId,businessIds));await db.delete(users).where(inArray(users.id,userIds));await db.delete(businesses).where(inArray(businesses.id,businessIds));await closeDatabase()}
