import { useCallback, useEffect, useMemo, useState } from 'react';
import { Banknote, CalendarDays, CircleDollarSign, Plus, ReceiptText, TrendingDown, TrendingUp } from 'lucide-react';
import { ModuleShell } from '@/components/shared/ModuleShell';
import { PageHeader } from '@/components/shared/PageHeader';
import { financeApi, type DuplicateWarning, type FinanceRecordInput } from '@/api/finance.api';
import { useAuthStore } from '@/store/auth.store';

const dateValue = (date: Date) => date.toISOString().slice(0, 10);
const initialForm = (currency: string): FinanceRecordInput => ({ recordType: 'expense', category: 'Operating costs', amountMinor: 0, currency, recordDate: dateValue(new Date()), supplierName: '', reference: '', notes: '' });
const categories = ['Ingredients & stock', 'Staff salary', 'Rent', 'Utilities', 'Delivery & transport', 'Maintenance', 'Fees', 'Marketing', 'Operating costs', 'Other'];

export const FinanceView = () => {
    const currency = useAuthStore(state => state.user?.currency) || 'USD';
    const [from, setFrom] = useState(() => dateValue(new Date(new Date().getFullYear(), new Date().getMonth(), 1)));
    const [to, setTo] = useState(() => dateValue(new Date()));
    const [records, setRecords] = useState<Awaited<ReturnType<typeof financeApi.list>>['records']>([]);
    const [summary, setSummary] = useState<Awaited<ReturnType<typeof financeApi.list>>['summary'] | null>(null);
    const [form, setForm] = useState(() => initialForm(currency));
    const [warnings, setWarnings] = useState<DuplicateWarning[]>([]);
    const [message, setMessage] = useState('');
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const money = useCallback((minor: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(minor / 100), [currency]);
    const load = useCallback(async () => { setLoading(true); try { const result = await financeApi.list(from, to); setRecords(result.records); setSummary(result.summary); setMessage(''); } catch { setMessage('Unable to load finance records.'); } finally { setLoading(false); } }, [from, to]);
    useEffect(() => { void load(); }, [load]);
    const active = useMemo(() => records.filter(record => record.status === 'saved'), [records]);
    const save = async (confirmDuplicate = false) => { if (!form.amountMinor || !form.category || !form.recordDate) return; setSaving(true); try { if (!confirmDuplicate) { const result = await financeApi.duplicateCheck(form); if (result.warnings.length) { setWarnings(result.warnings); return; } } await financeApi.create(form, confirmDuplicate); setForm(initialForm(currency)); setWarnings([]); setMessage('Cost record saved.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save this record.'); } finally { setSaving(false); } };
    return <ModuleShell><PageHeader title="Finance & Costs" subtitle="Track purchases, bills, salaries and operating costs, then compare them with paid revenue." />
        <div className="finance-controls"><label><CalendarDays size={16}/>From<input type="date" value={from} onChange={event => setFrom(event.target.value)} max={to}/></label><label>To<input type="date" value={to} onChange={event => setTo(event.target.value)} min={from}/></label></div>
        {message && <div className="finance-message">{message}</div>}
        <div className="finance-kpis"><article><CircleDollarSign/><span>Paid revenue</span><b>{money(summary?.revenueMinor || 0)}</b></article><article><TrendingDown/><span>Total costs</span><b>{money(summary?.totalCostsMinor || 0)}</b></article><article className={(summary?.netProfitMinor || 0) >= 0 ? 'positive' : 'negative'}><TrendingUp/><span>Net profit / loss</span><b>{money(summary?.netProfitMinor || 0)}</b></article></div>
        <div className="finance-layout"><section className="finance-form"><h2><Plus size={20}/> Add cost</h2><div className="finance-type"><button type="button" className={form.recordType === 'expense' ? 'active' : ''} onClick={() => setForm({...form, recordType:'expense'})}>Expense / bill</button><button type="button" className={form.recordType === 'purchase' ? 'active' : ''} onClick={() => setForm({...form, recordType:'purchase'})}>Purchase</button></div><label>Category<select value={form.category} onChange={event => setForm({...form, category:event.target.value})}>{categories.map(category => <option key={category}>{category}</option>)}</select></label><label>Supplier or payee<input value={form.supplierName} onChange={event => setForm({...form, supplierName:event.target.value})} placeholder="Optional name"/></label><div className="finance-split"><label>Amount<input type="number" min="0.01" step="0.01" value={form.amountMinor ? form.amountMinor / 100 : ''} onChange={event => setForm({...form, amountMinor:Math.round(Number(event.target.value) * 100)})}/></label><label>Date<input type="date" value={form.recordDate} onChange={event => setForm({...form, recordDate:event.target.value})}/></label></div><label>Reference<input value={form.reference} onChange={event => setForm({...form, reference:event.target.value})} placeholder="Invoice or receipt number"/></label><label>Notes<textarea rows={3} value={form.notes} onChange={event => setForm({...form, notes:event.target.value})}/></label>{warnings.length > 0 && <div className="duplicate-warning"><strong>Possible duplicate</strong>{warnings.map(warning => <p key={`${warning.severity}-${warning.recordId}`}>{warning.message}</p>)}<button type="button" onClick={() => void save(true)} disabled={saving}>Save anyway</button></div>}<button className="finance-save" type="button" onClick={() => void save()} disabled={saving || !form.amountMinor}><Plus size={17}/>{saving ? 'Saving…' : 'Save cost'}</button></section>
        <section className="finance-list"><h2><ReceiptText size={20}/> Cost history</h2>{loading ? <p>Loading records…</p> : !active.length ? <div className="finance-empty"><Banknote size={34}/><b>No costs recorded in this range</b><span>Add salaries, bills, purchases or operating expenses.</span></div> : <div className="finance-table"><table><thead><tr><th>Date</th><th>Type</th><th>Category / payee</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{active.map(record => <tr key={record.id}><td>{record.recordDate}</td><td>{record.recordType}</td><td><b>{record.category}</b><small>{record.supplierName}</small></td><td>{record.reference || '—'}</td><td><b>{money(record.amountMinor)}</b></td></tr>)}</tbody></table></div>}</section></div>
        <style>{`.finance-controls{display:flex;gap:10px;margin-bottom:16px}.finance-controls label{display:flex;gap:8px;align-items:center;background:#fff;color:#475569;border:1px solid #d8dee8;padding:9px 12px;border-radius:10px;font-weight:700;font-size:12px}.finance-controls input{border:0;color:#0f172a}.finance-message{padding:12px 15px;background:#fff7ed;color:#9a3412;border-radius:10px;margin-bottom:14px}.finance-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:16px}.finance-kpis article{padding:18px;background:#fff;color:#0f172a;border-radius:14px;display:grid;grid-template-columns:42px 1fr;border:1px solid #e2e8f0}.finance-kpis svg{grid-row:1/3;color:#f97316}.finance-kpis span{color:#64748b;font-size:13px}.finance-kpis b{font-size:25px}.finance-kpis .positive b{color:#047857}.finance-kpis .negative b{color:#b91c1c}.finance-layout{display:grid;grid-template-columns:minmax(300px,420px) 1fr;gap:16px}.finance-form,.finance-list{background:#fff;color:#0f172a;border:1px solid #e2e8f0;border-radius:14px;padding:20px}.finance-form h2,.finance-list h2{display:flex;align-items:center;gap:8px;margin:0 0 16px;font-size:20px}.finance-form label{display:grid;gap:6px;margin-bottom:12px;font-size:12px;font-weight:800}.finance-form input,.finance-form select,.finance-form textarea{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:9px;padding:11px;background:#fff;color:#0f172a;font:inherit}.finance-type{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:14px}.finance-type button{padding:11px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;font-weight:800}.finance-type button.active{background:#fff7ed;border-color:#f97316;color:#c2410c}.finance-split{display:grid;grid-template-columns:1fr 1fr;gap:10px}.finance-save,.duplicate-warning button{width:100%;min-height:44px;border:0;border-radius:9px;background:#f97316;color:#fff;font-weight:800;display:flex;justify-content:center;align-items:center;gap:7px}.duplicate-warning{padding:12px;margin-bottom:12px;border:1px solid #fbbf24;background:#fffbeb;border-radius:9px;color:#92400e}.duplicate-warning p{margin:5px 0;font-size:12px}.finance-empty{min-height:240px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#64748b;text-align:center}.finance-table{overflow:auto}.finance-table table{width:100%;border-collapse:collapse;min-width:620px}.finance-table th,.finance-table td{text-align:left;padding:12px;border-bottom:1px solid #e2e8f0;font-size:13px}.finance-table th{color:#64748b}.finance-table small{display:block;color:#64748b;margin-top:3px}@media(max-width:900px){.finance-layout{grid-template-columns:1fr}.finance-kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.finance-kpis{grid-template-columns:1fr}.finance-controls{flex-direction:column}.finance-controls label{justify-content:space-between}.finance-split{grid-template-columns:1fr}.finance-form,.finance-list{padding:15px}}`}</style>
    </ModuleShell>;
};
