export type ModuleStatus = 'enabled' | 'disabled' | 'preview' | 'locked';

export type ModuleRiskLevel = 'low' | 'medium' | 'high' | 'safety-sensitive';

export type WorkspaceKey =
    | 'restaurant'
    | 'retail'
    | 'pharmacy'
    | 'supermarket'
    | 'school'
    | 'services'
    | 'shared';

export type ModuleCategory =
    | 'dashboard'
    | 'commerce'
    | 'operations'
    | 'restaurant'
    | 'inventory'
    | 'crm'
    | 'documents'
    | 'team'
    | 'reports'
    | 'settings'
    | 'education'
    | 'future';

export interface Q360ModuleDefinition {
    moduleKey: string;
    workspaceKey: WorkspaceKey;
    label: string;
    description: string;
    status: ModuleStatus;
    category: ModuleCategory;
    isShared: boolean;
    riskLevel: ModuleRiskLevel;
    routePath?: string;
}

export interface Q360WorkspaceDefinition {
    workspaceKey: WorkspaceKey;
    label: string;
    description: string;
    status: ModuleStatus;
}

export const q360WorkspaceRegistry: readonly Q360WorkspaceDefinition[] = [
    {
        workspaceKey: 'restaurant',
        label: 'Restaurant',
        description: 'Active workspace for POS, menu, tables, KDS, payments, and reports.',
        status: 'enabled',
    },
    {
        workspaceKey: 'retail',
        label: 'Retail',
        description: 'Commerce workspace with shared Customers and Quotes enabled.',
        status: 'enabled',
    },
    {
        workspaceKey: 'pharmacy',
        label: 'Pharmacy',
        description: 'Preview template for pharmacy-like stock workflows. Not validated production pharmacy compliance.',
        status: 'preview',
    },
    {
        workspaceKey: 'supermarket',
        label: 'Supermarket',
        description: 'Internal preview commerce template for supermarket workflows.',
        status: 'preview',
    },
    {
        workspaceKey: 'school',
        label: 'School',
        description: 'Preview education template with dashboard foundation only.',
        status: 'preview',
    },
    {
        workspaceKey: 'services',
        label: 'Services',
        description: 'Future services template for jobs, tasks, materials, projects, quotes, and invoices.',
        status: 'disabled',
    },
    {
        workspaceKey: 'shared',
        label: 'Shared Modules',
        description: 'Cross-workspace module definitions that templates can reuse later.',
        status: 'locked',
    },
];

export const q360ModuleRegistry: readonly Q360ModuleDefinition[] = [
    {
        moduleKey: 'dashboard',
        workspaceKey: 'restaurant',
        label: 'Dashboard',
        description: 'Restaurant operating snapshot backed by current Restaurant data.',
        status: 'locked',
        category: 'dashboard',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/restaurant',
    },
    {
        moduleKey: 'pos',
        workspaceKey: 'restaurant',
        label: 'POS',
        description: 'Active Restaurant order entry for dine-in and takeaway flows.',
        status: 'enabled',
        category: 'restaurant',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/restaurant/pos',
    },
    {
        moduleKey: 'menu',
        workspaceKey: 'restaurant',
        label: 'Menu',
        description: 'Active Restaurant menu used by POS and kitchen workflows.',
        status: 'enabled',
        category: 'restaurant',
        isShared: false,
        riskLevel: 'medium',
        routePath: '/app/restaurant/menu',
    },
    {
        moduleKey: 'tables',
        workspaceKey: 'restaurant',
        label: 'Tables',
        description: 'Active floor and table management for dine-in Restaurant workflows.',
        status: 'enabled',
        category: 'restaurant',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/restaurant/floor',
    },
    {
        moduleKey: 'kds',
        workspaceKey: 'restaurant',
        label: 'KDS',
        description: 'Active kitchen display lifecycle for Restaurant tickets.',
        status: 'enabled',
        category: 'restaurant',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/restaurant/kitchen',
    },
    {
        moduleKey: 'payments',
        workspaceKey: 'restaurant',
        label: 'Payments',
        description: 'Active Restaurant order payment and billing surface.',
        status: 'enabled',
        category: 'restaurant',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/restaurant/billing',
    },
    {
        moduleKey: 'daily-report',
        workspaceKey: 'restaurant',
        label: 'Daily Report',
        description: 'Active Restaurant reporting surface for daily operations.',
        status: 'enabled',
        category: 'reports',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/restaurant/reports',
    },
    {
        moduleKey: 'inventory',
        workspaceKey: 'restaurant',
        label: 'Inventory',
        description: 'Restaurant inventory preview until Restaurant stock flows are backend-connected and validated.',
        status: 'preview',
        category: 'inventory',
        isShared: true,
        riskLevel: 'high',
        routePath: '/app/restaurant/inventory',
    },
    {
        moduleKey: 'staff',
        workspaceKey: 'restaurant',
        label: 'Staff',
        description: 'Restaurant staff preview until persistent staff management is ready.',
        status: 'preview',
        category: 'team',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/restaurant/staff',
    },
    {
        moduleKey: 'shifts-duties',
        workspaceKey: 'restaurant',
        label: 'Shifts / Duties',
        description: 'Restaurant shifts and duties preview until persistent scheduling is ready.',
        status: 'preview',
        category: 'team',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/restaurant/staff',
    },
    {
        moduleKey: 'settings',
        workspaceKey: 'restaurant',
        label: 'Settings',
        description: 'Restaurant settings surface. Future module settings should not alter lifecycle behavior.',
        status: 'locked',
        category: 'settings',
        isShared: false,
        riskLevel: 'medium',
        routePath: '/app/restaurant/settings',
    },
    {
        moduleKey: 'dashboard',
        workspaceKey: 'retail',
        label: 'Dashboard',
        description: 'Retail workspace dashboard.',
        status: 'locked',
        category: 'dashboard',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/retail',
    },
    {
        moduleKey: 'pos',
        workspaceKey: 'retail',
        label: 'Point of Sale',
        description: 'Retail POS surface currently available in the Retail workspace.',
        status: 'preview',
        category: 'commerce',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/retail/pos',
    },
    {
        moduleKey: 'catalog',
        workspaceKey: 'retail',
        label: 'Product Catalog',
        description: 'Retail product catalog surface.',
        status: 'preview',
        category: 'commerce',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/retail/catalog',
    },
    {
        moduleKey: 'inventory',
        workspaceKey: 'retail',
        label: 'Inventory',
        description: 'Retail inventory surface. Stock writes remain a high-risk module area.',
        status: 'preview',
        category: 'inventory',
        isShared: true,
        riskLevel: 'high',
        routePath: '/app/retail/inventory',
    },
    {
        moduleKey: 'customers',
        workspaceKey: 'retail',
        label: 'Customers',
        description: 'Backend-connected shared customer records for Commerce and future Services.',
        status: 'enabled',
        category: 'crm',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/retail/customers',
    },
    {
        moduleKey: 'quotes',
        workspaceKey: 'retail',
        label: 'Quotes',
        description: 'Backend-connected shared quotes with tenant-scoped customers and quote items.',
        status: 'enabled',
        category: 'documents',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/retail/quotes',
    },
    {
        moduleKey: 'procurement',
        workspaceKey: 'retail',
        label: 'Procurement',
        description: 'Retail procurement surface for supplier ordering workflows.',
        status: 'preview',
        category: 'operations',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/retail/procurement',
    },
    {
        moduleKey: 'reports',
        workspaceKey: 'retail',
        label: 'Reports',
        description: 'Retail reports surface.',
        status: 'preview',
        category: 'reports',
        isShared: true,
        riskLevel: 'low',
        routePath: '/app/retail/reports',
    },
    {
        moduleKey: 'settings',
        workspaceKey: 'retail',
        label: 'Settings',
        description: 'Retail settings surface.',
        status: 'locked',
        category: 'settings',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/retail/settings',
    },
    {
        moduleKey: 'catalog',
        workspaceKey: 'pharmacy',
        label: 'Medicine / Product Catalog',
        description: 'Preview pharmacy-like catalog. Not validated production pharmacy compliance.',
        status: 'preview',
        category: 'inventory',
        isShared: true,
        riskLevel: 'safety-sensitive',
        routePath: '/app/pharmacy/catalog',
    },
    {
        moduleKey: 'inventory',
        workspaceKey: 'pharmacy',
        label: 'Medicine / Product Stock',
        description: 'Preview stock concepts for pharmacy-like products; batch, expiry, and safety rules need validation.',
        status: 'preview',
        category: 'inventory',
        isShared: true,
        riskLevel: 'safety-sensitive',
        routePath: '/app/pharmacy/inventory',
    },
    {
        moduleKey: 'suppliers',
        workspaceKey: 'pharmacy',
        label: 'Suppliers',
        description: 'Preview supplier surface for pharmacy template workflows.',
        status: 'preview',
        category: 'operations',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/pharmacy/suppliers',
    },
    {
        moduleKey: 'procurement',
        workspaceKey: 'pharmacy',
        label: 'Procurement',
        description: 'Preview procurement surface for pharmacy template workflows.',
        status: 'preview',
        category: 'operations',
        isShared: true,
        riskLevel: 'high',
        routePath: '/app/pharmacy/procurement',
    },
    {
        moduleKey: 'dispensing',
        workspaceKey: 'pharmacy',
        label: 'Dispensing',
        description: 'Preview dispensing-like surface; not validated for production medical or pharmacy use.',
        status: 'preview',
        category: 'commerce',
        isShared: false,
        riskLevel: 'safety-sensitive',
        routePath: '/app/pharmacy/pos',
    },
    {
        moduleKey: 'prescriptions',
        workspaceKey: 'pharmacy',
        label: 'Prescriptions',
        description: 'Preview prescription-like surface; compliance and safety requirements are not validated.',
        status: 'preview',
        category: 'documents',
        isShared: false,
        riskLevel: 'safety-sensitive',
        routePath: '/app/pharmacy/rx',
    },
    {
        moduleKey: 'staff',
        workspaceKey: 'pharmacy',
        label: 'Staff',
        description: 'Preview staff surface for pharmacy template workflows.',
        status: 'preview',
        category: 'team',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/pharmacy/staff',
    },
    {
        moduleKey: 'reports',
        workspaceKey: 'pharmacy',
        label: 'Reports',
        description: 'Preview reports surface for pharmacy template workflows.',
        status: 'preview',
        category: 'reports',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/pharmacy/reports',
    },
    {
        moduleKey: 'pos',
        workspaceKey: 'supermarket',
        label: 'Barcode POS',
        description: 'Internal preview POS surface for supermarket workflows.',
        status: 'preview',
        category: 'commerce',
        isShared: false,
        riskLevel: 'high',
        routePath: '/app/supermarket/pos',
    },
    {
        moduleKey: 'catalog',
        workspaceKey: 'supermarket',
        label: 'Product Catalog',
        description: 'Internal preview supermarket catalog surface.',
        status: 'preview',
        category: 'commerce',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/supermarket/catalog',
    },
    {
        moduleKey: 'inventory',
        workspaceKey: 'supermarket',
        label: 'Inventory',
        description: 'Internal preview supermarket inventory surface.',
        status: 'preview',
        category: 'inventory',
        isShared: true,
        riskLevel: 'high',
        routePath: '/app/supermarket/inventory',
    },
    {
        moduleKey: 'procurement',
        workspaceKey: 'supermarket',
        label: 'Procurement',
        description: 'Internal preview supermarket procurement surface.',
        status: 'preview',
        category: 'operations',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/supermarket/procurement',
    },
    {
        moduleKey: 'suppliers',
        workspaceKey: 'supermarket',
        label: 'Suppliers',
        description: 'Internal preview supplier management surface.',
        status: 'preview',
        category: 'operations',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/supermarket/suppliers',
    },
    {
        moduleKey: 'offers',
        workspaceKey: 'supermarket',
        label: 'Offers & Pricing',
        description: 'Internal preview offers and pricing surface.',
        status: 'preview',
        category: 'commerce',
        isShared: false,
        riskLevel: 'medium',
        routePath: '/app/supermarket/offers',
    },
    {
        moduleKey: 'staff-shifts',
        workspaceKey: 'supermarket',
        label: 'Staff & Shifts',
        description: 'Internal preview staff and shift surface.',
        status: 'preview',
        category: 'team',
        isShared: true,
        riskLevel: 'medium',
        routePath: '/app/supermarket/staff',
    },
    {
        moduleKey: 'reports',
        workspaceKey: 'supermarket',
        label: 'Reports',
        description: 'Internal preview supermarket reports surface.',
        status: 'preview',
        category: 'reports',
        isShared: true,
        riskLevel: 'low',
        routePath: '/app/supermarket/reports',
    },
    {
        moduleKey: 'settings',
        workspaceKey: 'supermarket',
        label: 'Settings',
        description: 'Internal preview supermarket settings surface.',
        status: 'preview',
        category: 'settings',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/supermarket/settings',
    },
    {
        moduleKey: 'dashboard',
        workspaceKey: 'school',
        label: 'Dashboard',
        description: 'Preview school dashboard foundation.',
        status: 'preview',
        category: 'education',
        isShared: false,
        riskLevel: 'low',
        routePath: '/app/school',
    },
    {
        moduleKey: 'customers',
        workspaceKey: 'shared',
        label: 'Customers',
        description: 'Shared customer/client records for Commerce and future Services.',
        status: 'enabled',
        category: 'crm',
        isShared: true,
        riskLevel: 'medium',
    },
    {
        moduleKey: 'quotes',
        workspaceKey: 'shared',
        label: 'Quotes',
        description: 'Shared estimates and quote documents for Commerce and future Services.',
        status: 'enabled',
        category: 'documents',
        isShared: true,
        riskLevel: 'medium',
    },
    {
        moduleKey: 'projects',
        workspaceKey: 'shared',
        label: 'Projects',
        description: 'Future shared optional module for multi-step jobs. Not a separate top-level workspace.',
        status: 'disabled',
        category: 'future',
        isShared: true,
        riskLevel: 'medium',
    },
    {
        moduleKey: 'tasks',
        workspaceKey: 'shared',
        label: 'Tasks',
        description: 'Future shared module for assignments, service work, duties, and follow-up.',
        status: 'disabled',
        category: 'future',
        isShared: true,
        riskLevel: 'medium',
    },
    {
        moduleKey: 'documents',
        workspaceKey: 'shared',
        label: 'Documents',
        description: 'Future shared document surface for quotes, invoices, job files, and attachments.',
        status: 'disabled',
        category: 'future',
        isShared: true,
        riskLevel: 'low',
    },
    {
        moduleKey: 'business-pulse',
        workspaceKey: 'shared',
        label: 'Business Pulse',
        description: 'Future shared read-only insight layer over enabled and permitted module data.',
        status: 'preview',
        category: 'future',
        isShared: true,
        riskLevel: 'medium',
    },
];

export const getQ360ModulesByWorkspace = (workspaceKey: WorkspaceKey) =>
    q360ModuleRegistry.filter(module => module.workspaceKey === workspaceKey);

export const getQ360ModuleDefinition = (workspaceKey: WorkspaceKey, moduleKey: string) =>
    q360ModuleRegistry.find(module => module.workspaceKey === workspaceKey && module.moduleKey === moduleKey);

export const getQ360ModulesByStatus = (status: ModuleStatus) =>
    q360ModuleRegistry.filter(module => module.status === status);
