import { randomUUID } from 'crypto';
import { Hono } from 'hono';
import { and, desc, eq } from 'drizzle-orm';
import { db, first } from '../db/client.js';
import { businesses, staffInvitations, staffMembers, users } from '../db/schema.js';
import { authMiddleware, requireRole } from '../middleware/auth.js';
import type { AppEnv } from '../types/app.js';
import { logAudit } from '../utils/audit.js';
import { sendStaffInvitationEmail } from '../services/email.js';

const staff=new Hono<AppEnv>(); staff.use('*',authMiddleware); const roles=['manager','waiter','cashier','kitchen','staff'] as const; const modules=new Set(['dashboard','pos','kds','menu','tables','inventory','payments','daily-report','staff']);
staff.get('/',requireRole(['user','owner','admin','manager']),async c=>c.json(await db.select().from(staffMembers).where(eq(staffMembers.businessId,c.get('businessId'))).orderBy(desc(staffMembers.createdAt))));
staff.post('/invite',requireRole(['user','owner','admin','manager']),async c=>{let body:{name?:unknown;email?:unknown;role?:unknown;moduleAccess?:unknown;shiftName?:unknown;shiftStart?:unknown;shiftEnd?:unknown};try{body=await c.req.json()}catch{return c.json({error:'Invalid JSON body'},400)}
 const name=typeof body.name==='string'?body.name.trim():'',email=typeof body.email==='string'?body.email.trim().toLowerCase():'',role=typeof body.role==='string'?body.role:'';if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!roles.includes(role as typeof roles[number]))return c.json({error:'Name, valid email, and staff role are required'},400);if(!Array.isArray(body.moduleAccess)||body.moduleAccess.some(x=>typeof x!=='string'||!modules.has(x)))return c.json({error:'Invalid module access'},400);
 const businessId=c.get('businessId');if(await first(db.select().from(staffMembers).where(and(eq(staffMembers.businessId,businessId),eq(staffMembers.email,email)))))return c.json({error:'Staff email already exists'},409);const memberId=randomUUID(),inviteId=randomUUID(),access=body.moduleAccess as string[];
 await db.transaction(async tx=>{await tx.insert(staffMembers).values({id:memberId,businessId,name,email,role,moduleAccess:access,shiftName:typeof body.shiftName==='string'?body.shiftName.trim()||null:null,shiftStart:typeof body.shiftStart==='string'?body.shiftStart:null,shiftEnd:typeof body.shiftEnd==='string'?body.shiftEnd:null,status:'invited'});await tx.insert(staffInvitations).values({id:inviteId,businessId,staffMemberId:memberId,email,role,moduleAccess:access,invitedBy:c.get('userId')})});
 const business=await first(db.select().from(businesses).where(eq(businesses.id,businessId)));let delivered=true;try{await sendStaffInvitationEmail(email,business?.name||'Your business',role)}catch{delivered=false}
 await logAudit(c,'STAFF_INVITED','STAFF',memberId,{email,role,moduleAccess:access,emailDelivered:delivered});return c.json({id:memberId,invitationId:inviteId,emailDelivered:delivered},201)});
staff.patch('/:id',requireRole(['user','owner','admin','manager']),async c=>{const id=c.req.param('id');if(!id)return c.json({error:'Staff ID required'},400);let body:{name?:unknown;status?:unknown;role?:unknown;moduleAccess?:unknown;shiftName?:unknown;shiftStart?:unknown;shiftEnd?:unknown};try{body=await c.req.json()}catch{return c.json({error:'Invalid JSON body'},400)}const businessId=c.get('businessId'),member=await first(db.select().from(staffMembers).where(and(eq(staffMembers.id,id),eq(staffMembers.businessId,businessId))));if(!member)return c.json({error:'Staff member not found'},404);const name=body.name===undefined?member.name:typeof body.name==='string'?body.name.trim():'';if(!name)return c.json({error:'Staff name is required'},400);if(body.role!==undefined&&(typeof body.role!=='string'||!roles.includes(body.role as typeof roles[number])))return c.json({error:'Invalid role'},400);if(body.moduleAccess!==undefined&&(!Array.isArray(body.moduleAccess)||body.moduleAccess.some(x=>typeof x!=='string'||!modules.has(x))))return c.json({error:'Invalid module access'},400);if(body.status!==undefined&&!['active','inactive','invited'].includes(String(body.status)))return c.json({error:'Invalid status'},400);const nextRole=typeof body.role==='string'?body.role:member.role,nextAccess=Array.isArray(body.moduleAccess)?body.moduleAccess as string[]:member.moduleAccess,nextStatus=typeof body.status==='string'?body.status as 'active'|'inactive'|'invited':member.status;let updated:typeof member|undefined;await db.transaction(async tx=>{[updated]=await tx.update(staffMembers).set({name,role:nextRole,moduleAccess:nextAccess,status:nextStatus,shiftName:typeof body.shiftName==='string'?body.shiftName.trim()||null:member.shiftName,shiftStart:typeof body.shiftStart==='string'?body.shiftStart:member.shiftStart,shiftEnd:typeof body.shiftEnd==='string'?body.shiftEnd:member.shiftEnd,updatedAt:new Date()}).where(and(eq(staffMembers.id,id),eq(staffMembers.businessId,businessId))).returning();if(member.userId)await tx.update(users).set({name,role:nextRole,moduleAccess:nextAccess,status:nextStatus==='inactive'?'inactive':'active'}).where(and(eq(users.id,member.userId),eq(users.businessId,businessId)));if(member.status==='invited')await tx.update(staffInvitations).set({role:nextRole,moduleAccess:nextAccess,status:nextStatus==='inactive'?'revoked':'pending'}).where(and(eq(staffInvitations.staffMemberId,id),eq(staffInvitations.businessId,businessId),eq(staffInvitations.status,'pending')))});await logAudit(c,'STAFF_UPDATED','STAFF',id,{fields:Object.keys(body)});return c.json(updated)});
export default staff;
