import { useEffect, useMemo, useState } from 'react';
import { Clock3, MapPin, Search, UtensilsCrossed } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { publicApiBaseUrl } from '@/api/http';

type PublicMenu = { business:{publicCode:string;name:string;country:string|null;city:string|null;currency:string;logoUrl:string|null};categories:{id:string;name:string;items:{id:string;name:string;description:string|null;imageUrl:string|null;price:number;prepTimeMinutes:number}[]}[] };

export const PublicMenuView = () => {
    const { publicCode = '' } = useParams();
    const [menu,setMenu]=useState<PublicMenu|null>(null); const [error,setError]=useState(''); const [query,setQuery]=useState('');
    useEffect(()=>{ fetch(`${publicApiBaseUrl}/public/businesses/${encodeURIComponent(publicCode)}/menu`).then(async response=>{if(!response.ok)throw new Error('This menu is not available.');return response.json() as Promise<PublicMenu>}).then(setMenu).catch(error=>setError(error instanceof Error?error.message:'Unable to load menu')); },[publicCode]);
    const categories=useMemo(()=>menu?.categories.map(category=>({...category,items:category.items.filter(item=>`${item.name} ${item.description||''}`.toLowerCase().includes(query.trim().toLowerCase()))})).filter(category=>category.items.length)||[],[menu,query]);
    if(error)return <div className="public-menu-state"><UtensilsCrossed size={40}/><h1>Menu unavailable</h1><p>{error}</p></div>;
    if(!menu)return <div className="public-menu-state">Loading menu…</div>;
    const money=(cents:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:menu.business.currency||'USD'}).format(cents/100);
    return <div className="public-menu-page"><header><div className="public-brand">{menu.business.logoUrl?<img src={menu.business.logoUrl} alt=""/>:<div><UtensilsCrossed size={27}/></div>}<span><h1>{menu.business.name}</h1>{(menu.business.city||menu.business.country)&&<small><MapPin size={12}/>{[menu.business.city,menu.business.country].filter(Boolean).join(', ')}</small>}</span></div><p>Explore our currently available menu.</p><label><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search the menu"/></label></header><main>{categories.map(category=><section key={category.id}><h2>{category.name}</h2><div>{category.items.map(item=><article key={item.id}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<div className="public-item-placeholder"><UtensilsCrossed size={25}/></div>}<div className="public-item-copy"><div><h3>{item.name}</h3><strong>{money(item.price)}</strong></div>{item.description&&<p>{item.description}</p>}{item.prepTimeMinutes>0&&<small><Clock3 size={12}/>{item.prepTimeMinutes} min</small>}</div></article>)}</div></section>)}{!categories.length&&<div className="public-menu-empty">No menu items match your search.</div>}</main><footer>Menu powered by Q360 · {menu.business.publicCode}</footer><style>{`
    .public-menu-page{min-height:100vh;background:#f7f3ed;color:#172033;font-family:var(--font-sans);padding-bottom:50px}.public-menu-page>header{padding:28px max(20px,calc((100vw - 960px)/2));background:#18221e;color:#fff}.public-brand{display:flex;align-items:center;gap:13px}.public-brand img,.public-brand>div{width:54px;height:54px;display:grid;place-items:center;border-radius:13px;background:#fff;object-fit:contain}.public-brand h1{margin:0;font-size:25px}.public-brand small{display:flex;align-items:center;gap:4px;margin-top:3px;color:#cbd5c0}.public-menu-page header>p{margin:16px 0;color:#d7ded5}.public-menu-page header label{max-width:480px;display:flex;align-items:center;gap:8px;padding:0 13px;border:1px solid #4a5a51;border-radius:12px;background:#fff;color:#64748b}.public-menu-page header input{width:100%;height:44px;border:0;outline:0;font:inherit}.public-menu-page main{max-width:960px;margin:auto;padding:26px 20px}.public-menu-page section{margin-bottom:32px}.public-menu-page section h2{margin:0 0 14px;font-size:22px}.public-menu-page section>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.public-menu-page article{min-height:125px;display:grid;grid-template-columns:125px minmax(0,1fr);overflow:hidden;border:1px solid #e4ddd4;border-radius:16px;background:#fff;box-shadow:0 5px 16px rgba(35,28,20,.04)}.public-menu-page article>img,.public-item-placeholder{width:125px;height:100%;min-height:125px;object-fit:cover;background:#ede8df;display:grid;place-items:center;color:#9b8f80}.public-item-copy{padding:15px}.public-item-copy>div{display:flex;justify-content:space-between;gap:10px}.public-item-copy h3{margin:0;font-size:16px}.public-item-copy strong{color:#c2521b;white-space:nowrap}.public-item-copy p{margin:9px 0;color:#6b7280;font-size:12px;line-height:1.45}.public-item-copy small{display:flex;align-items:center;gap:4px;color:#8a7767}.public-menu-empty{text-align:center;padding:50px;color:#6b7280}.public-menu-page footer{text-align:center;color:#8a8178;font-size:11px}.public-menu-state{min-height:100vh;display:grid;place-content:center;text-align:center;background:#f7f3ed;color:#475569}.public-menu-state h1{margin-bottom:0}@media(max-width:700px){.public-menu-page section>div{grid-template-columns:1fr}.public-menu-page article{grid-template-columns:95px minmax(0,1fr)}.public-menu-page article>img,.public-item-placeholder{width:95px}}
    `}</style></div>;
};
